fix ci collecting error

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -88,7 +88,7 @@ jobs:
             log_level=INFO
           fi
           uv run pytest tests/unit_tests/ -v --log-cli-level=${log_level} | tee pytest.log
-          tail -n 1 pytest.log | grep -q 'failed' && exit 1 || exit 0
+          tail -n 1 pytest.log | grep '=======' | grep 'passed' |grep -q 'failed' && exit 1 || exit 0
 
       - name: Run integration tests without any test mode
         run: |
@@ -98,7 +98,7 @@ jobs:
             log_level=INFO
           fi
           uv run pytest tests/integration_tests/ -v --log-cli-level=${log_level} -k "not server and not embedded and not oceanbase" | tee pytest.log
-          tail -n 1 pytest.log | grep -q 'failed' && exit 1 || exit 0
+          tail -n 1 pytest.log | grep '=======' | grep 'passed' | grep -q 'failed' && exit 1 || exit 0
 
   integration-test:
     runs-on: ubuntu-latest
@@ -160,4 +160,4 @@ jobs:
             log_level=INFO
           fi
           uv run pytest tests/integration_tests/ -v --log-cli-level=${log_level} -k "${{ matrix.test_mode }}" | tee pytest.log
-          tail -n 1 pytest.log | grep -q 'failed' && exit 1 || exit 0
+          tail -n 1 pytest.log | grep '=======' | grep 'passed' | grep -q 'failed' && exit 1 || exit 0
