ruff check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -59,6 +59,16 @@ jobs:
           uv run pytest tests/unit_tests/ -v --log-cli-level=${log_level} | tee pytest.log
           tail -n 1 pytest.log | grep -q 'failed' && exit 1 || exit 0
 
+      - name: Run integration tests without any test mode
+        run: |
+          if [ "${{ env.RUNNER_DEBUG }}" = "true" ]; then
+            log_level=DEBUG
+          else
+            log_level=INFO
+          fi
+          uv run pytest tests/integration_tests/ -v --log-cli-level=${log_level} -k "not server and not embedded and not oceanbase" | tee pytest.log
+          tail -n 1 pytest.log | grep -q 'failed' && exit 1 || exit 0
+
   integration-test:
     runs-on: ubuntu-latest
     strategy:
