fix ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,7 +56,8 @@ jobs:
           else
             log_level=INFO
           fi
-          uv run pytest tests/unit_tests/ -v --log-cli-level=${log_level}
+          uv run pytest tests/unit_tests/ -v --log-cli-level=${log_level} | tee pytest.log
+          tail -n 1 pytest.log | grep -q 'failed' && exit 1 || exit 0
 
   integration-test:
     runs-on: ubuntu-latest
@@ -117,4 +118,5 @@ jobs:
           else
             log_level=INFO
           fi
-          uv run pytest tests/integration_tests/ -v --log-cli-level=${log_level} -k "${{ matrix.test_mode }}"
+          uv run pytest tests/integration_tests/ -v --log-cli-level=${log_level} -k "${{ matrix.test_mode }}" | tee pytest.log
+          tail -n 1 pytest.log | grep -q 'failed' && exit 1 || exit 0
